/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 24-sep.-2020 22:00:41 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */


/*DROP TABLE IF EXISTS `aula` CASCADE
;

DROP TABLE IF EXISTS `aulas_materias` CASCADE
;

DROP TABLE IF EXISTS `evaluacion` CASCADE
;

DROP TABLE IF EXISTS `inscripcion` CASCADE
;

DROP TABLE IF EXISTS `instancia_evaluacion` CASCADE
;

DROP TABLE IF EXISTS `materia` CASCADE
;

DROP TABLE IF EXISTS `nota_alumno` CASCADE
;

DROP TABLE IF EXISTS `usuario` CASCADE
;*/

/* Create Tables */

CREATE TABLE `aula`
(
	`id_aula` INT(11) NOT NULL,
	`nombre_aula` VARCHAR(50) NOT NULL,
	`estado` VARCHAR(10) NOT NULL DEFAULT 'ACTIVO',
	`id_secuser` INT(11) NULL,
	`dt_last_update` DATETIME NULL,
	CONSTRAINT `PK_Aula` PRIMARY KEY (`id_aula` ASC)
)

;

CREATE TABLE `aulas_materias`
(
	`id_aula` INT(11) NOT NULL,
	`id_materia` INT(11) NOT NULL,
	`anho` VARCHAR(50) NOT NULL,
	`id_rel` INT(11) NOT NULL,
	`id_docente` INT(11) NULL,
	`estado` VARCHAR(10) NOT NULL DEFAULT 'ACTIVO',
	`id_secuser` INT(11) NULL,
	`dt_last_update` DATETIME NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_rel` ASC)
)

;

CREATE TABLE `evaluacion`
(
	`id_evaluacion` INT(11) NOT NULL,
	`id_materia` INT(11) NOT NULL,
	`id_instancia` INT(11) NOT NULL,
	`fecha` DATE NOT NULL,
	`estado` VARCHAR(10) NOT NULL DEFAULT 'ACTIVO',
	`id_secuser` INT(11) NULL,
	`dt_last_update` DATETIME NULL,
	CONSTRAINT `PK_evaluacion` PRIMARY KEY (`id_evaluacion` ASC)
)

;

CREATE TABLE `inscripcion`
(
	`id_inscripcion` INT(11) NOT NULL,
	`id_alumno` INT(11) NULL,
	`id_aula_materia` INT(11) NULL,
	`estado` VARCHAR(10) NOT NULL DEFAULT 'ACTIVO',
	`id_secuser` INT(11) NULL,
	`dt_last_update` DATETIME NULL,
	CONSTRAINT `PK_inscripcion` PRIMARY KEY (`id_inscripcion` ASC)
)

;

CREATE TABLE `instancia_evaluacion`
(
	`id_instancia` INT(11) NOT NULL,
	`nombre_instancia` VARCHAR(255) NOT NULL,
	`estado` VARCHAR(10) NOT NULL DEFAULT 'ACTIVO',
	CONSTRAINT `PK_instancia_evaluacion` PRIMARY KEY (`id_instancia` ASC)
)

;

CREATE TABLE `materia` (
  `id_materia` int(11) NOT NULL,
  `nombre_materia` varchar(50) NOT NULL,
  `dia` varchar(10) NOT NULL,
  `horario` varchar(20) NOT NULL,
  `estado` varchar(10) NOT NULL DEFAULT 'ACTIVO',
  `id_secuser` INT(11) NULL,
  `dt_last_update` DATETIME NULL,
	CONSTRAINT `PK_materia` PRIMARY KEY (`id_materia` ASC)
)

;

CREATE TABLE `nota_alumno` (
  `id_nota` int(11) NOT NULL,
  `id_inscripcion` int(11) DEFAULT NULL,
  `id_instancia` int(11) DEFAULT NULL,
  `nota` varchar(50) DEFAULT NULL,
  `estado` varchar(10) NOT NULL DEFAULT 'ACTIVO',
  `id_secuser` INT(11) NULL,
  `dt_last_update` DATETIME NULL,
	CONSTRAINT `PK_nota_alumno` PRIMARY KEY (`id_nota` ASC)
)

;

	CREATE TABLE `usuario` (
  `id_usuario` int(11) NOT NULL,
  `nombre` varchar(50) NOT NULL,
  `apellido` varchar(50) NOT NULL,
  `direccion` varchar(100) NOT NULL,
  `email` varchar(255) NOT NULL,
  `dni` varchar(10) NOT NULL,
  `contraseña` varchar(255) NOT NULL,
  `cuit_cuil` varchar(15) NOT NULL,
  `rol` varchar(11) NOT NULL,
  `fecha_nac` date NOT NULL,
  `edad` varchar(3) NOT NULL,
  `estado` varchar(10) NOT NULL DEFAULT 'ACTIVO',
  `id_secuser` INT(11) NULL,
  `dt_last_update` DATETIME NULL,
	CONSTRAINT `PK_Usuario` PRIMARY KEY (`id_usuario` ASC)
)

;


ALTER TABLE `aula`
  MODIFY `id_aula` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `aulas_materias`
--
ALTER TABLE `aulas_materias`
  MODIFY `id_rel` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `evaluacion`
--
ALTER TABLE `evaluacion`
  MODIFY `id_evaluacion` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `inscripcion`
--
ALTER TABLE `inscripcion`
  MODIFY `id_inscripcion` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `instancia_evaluacion`
--
ALTER TABLE `instancia_evaluacion`
  MODIFY `id_instancia` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `materia`
--
ALTER TABLE `materia`
  MODIFY `id_materia` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `nota_alumno`
--
ALTER TABLE `nota_alumno`
  MODIFY `id_nota` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `usuario`
--
ALTER TABLE `usuario`
  MODIFY `id_usuario` int(11) NOT NULL AUTO_INCREMENT;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `aulas_materias` 
 ADD CONSTRAINT `unique` UNIQUE (`anho` ASC, `id_materia` ASC, `id_aula` ASC)
;

ALTER TABLE `aulas_materias` 
 ADD INDEX `IXFK_aulas_materias_aula` (`id_aula` ASC)
;

ALTER TABLE `aulas_materias` 
 ADD INDEX `IXFK_aulas_materias_docente` (`id_docente` ASC)
;

ALTER TABLE `aulas_materias` 
 ADD INDEX `IXFK_aulas_materias_materia` (`id_materia` ASC)
;

ALTER TABLE `evaluacion` 
 ADD INDEX `IXFK_evaluacion_materia` (`id_materia` ASC)
;

ALTER TABLE `evaluacion` 
 ADD INDEX `IXFK_evaluacion_instancia` (`id_instancia` ASC)
;

ALTER TABLE `inscripcion` 
 ADD CONSTRAINT `Unique` UNIQUE (`id_alumno` ASC, `id_aula_materia` ASC)
;

ALTER TABLE `inscripcion` 
 ADD INDEX `IXFK_inscripcion_alumnos` (`id_alumno` ASC)
;

ALTER TABLE `inscripcion` 
 ADD INDEX `IXFK_inscripcion_aulas_materias` (`id_aula_materia` ASC)
;

ALTER TABLE `nota_alumno` 
 ADD CONSTRAINT `unica` UNIQUE (`id_inscripcion` ASC, `id_instancia` ASC)
;

ALTER TABLE `nota_alumno` 
 ADD INDEX `IXFK_nota_alumno_inscripcion` (`id_inscripcion` ASC)
;


ALTER TABLE `nota_alumno` 
 ADD INDEX `IXFK_nota_alumno_instancia_evaluacion` (`id_instancia` ASC)
;

/* Create Foreign Key Constraints */


ALTER TABLE `aulas_materias` 
 ADD CONSTRAINT `FK_aulas_materias_aula`
	FOREIGN KEY (`id_aula`) REFERENCES `aula` (`id_aula`) ON DELETE Restrict ON UPDATE Restrict
;


ALTER TABLE `aulas_materias` 
 ADD CONSTRAINT `FK_aulas_materias_materia`
	FOREIGN KEY (`id_materia`) REFERENCES `materia` (`id_materia`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `aulas_materias` 
 ADD CONSTRAINT `FK_aulas_materias_docente`
	FOREIGN KEY (`id_docente`) REFERENCES `usuario` (`id_usuario`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `evaluacion` 
 ADD CONSTRAINT `FK_evaluacion_materia`
	FOREIGN KEY (`id_materia`) REFERENCES `materia` (`id_materia`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `evaluacion` 
 ADD CONSTRAINT `FK_evaluacion_instancia`
	FOREIGN KEY (`id_instancia`) REFERENCES `instancia_evaluacion` (`id_instancia`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `inscripcion` 
 ADD CONSTRAINT `FK_inscripcion_alumnos`
	FOREIGN KEY (`id_alumno`) REFERENCES `usuario` (`id_usuario`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `inscripcion` 
 ADD CONSTRAINT `FK_inscripcion_aulas_materias`
	FOREIGN KEY (`id_aula_materia`) REFERENCES `aulas_materias` (`id_rel`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `nota_alumno` 
 ADD CONSTRAINT `FK_nota_alumno_inscripcion`
	FOREIGN KEY (`id_inscripcion`) REFERENCES `inscripcion` (`id_inscripcion`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `nota_alumno` 
 ADD CONSTRAINT `FK_nota_alumno_instancia_evaluacion`
	FOREIGN KEY (`id_instancia`) REFERENCES `instancia_evaluacion` (`id_instancia`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;

INSERT INTO `instancia_evaluacion` (`id_instancia`, `nombre_instancia`, `estado`) VALUES
(1, 'Primer Parcial', 'ACTIVO'),
(2, 'Segundo Parcial', 'ACTIVO'),
(3, 'Recuperatorio', 'ACTIVO'),
(4, 'Final', 'ACTIVO');

INSERT INTO `aula`(`nombre_aula`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('Aula 1','ACTIVO','1',SYSDATE());
INSERT INTO `aula`(`nombre_aula`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('Aula 2','ACTIVO','1',SYSDATE());
INSERT INTO `aula`(`nombre_aula`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('Aula 3','ACTIVO','1',SYSDATE());
INSERT INTO `aula`(`nombre_aula`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('Aula 4','ACTIVO','1',SYSDATE());
INSERT INTO `aula`(`nombre_aula`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('Aula 5','ACTIVO','1',SYSDATE());

INSERT INTO `materia`(`nombre_materia`, `dia`, `horario`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('Materia 1','Lunes','18:30','ACTIVO','1',sysdate());
INSERT INTO `materia`(`nombre_materia`, `dia`, `horario`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('Materia 2','Martes','18:30','ACTIVO','1',sysdate());
INSERT INTO `materia`(`nombre_materia`, `dia`, `horario`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('Materia 3','Miercoles','18:30','ACTIVO','1',sysdate());
INSERT INTO `materia`(`nombre_materia`, `dia`, `horario`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('Materia 4','Jueves','18:30','ACTIVO','1',sysdate());
INSERT INTO `materia`(`nombre_materia`, `dia`, `horario`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('Materia 5','Viernes','18:30','ACTIVO','1',sysdate());
INSERT INTO `materia`(`nombre_materia`, `dia`, `horario`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('Materia 6','Lunes','20:30','ACTIVO','1',sysdate());
INSERT INTO `materia`(`nombre_materia`, `dia`, `horario`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('Materia 7','Martes','20:30','ACTIVO','1',sysdate());
INSERT INTO `materia`(`nombre_materia`, `dia`, `horario`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('Materia 8','Miercoles','20:30','ACTIVO','1',sysdate());
INSERT INTO `materia`(`nombre_materia`, `dia`, `horario`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('Materia 9','Jueves','20:30','ACTIVO','1',sysdate());
INSERT INTO `materia`(`nombre_materia`, `dia`, `horario`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('Materia 10','Viernes','20:30','ACTIVO','1',sysdate());

INSERT INTO `usuario`(`nombre`, `apellido`, `direccion`, `email`, `dni`, `contraseña`, `cuit_cuil`, `rol`, `fecha_nac`, `edad`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('admin','admin','direccion admin 234','admin@admin.com','11222333','$2a$10$sT3IZvFLmODfSX82msbHb./lE3OU0.HhiARJ.iuMFfEtKmoQigAim','20112223337','ADMIN','1985/12/01','34','ACTIVO','1',sysdate());
INSERT INTO `usuario`(`nombre`, `apellido`, `direccion`, `email`, `dni`, `contraseña`, `cuit_cuil`, `rol`, `fecha_nac`, `edad`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('Alumno','Uno','direccion Alumno 1','alumno@uno.com','22111333','$2a$10$sT3IZvFLmODfSX82msbHb./lE3OU0.HhiARJ.iuMFfEtKmoQigAim','20221113337','ESTUDIANTE','1995/06/10','25','ACTIVO','1',sysdate());
INSERT INTO `usuario`(`nombre`, `apellido`, `direccion`, `email`, `dni`, `contraseña`, `cuit_cuil`, `rol`, `fecha_nac`, `edad`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('Alumno','Dos','direccion Alumno 2','alumno@dos.com','33111444','$2a$10$sT3IZvFLmODfSX82msbHb./lE3OU0.HhiARJ.iuMFfEtKmoQigAim','20331114447','ESTUDIANTE','2000/03/23','20','ACTIVO','1',sysdate());
INSERT INTO `usuario`(`nombre`, `apellido`, `direccion`, `email`, `dni`, `contraseña`, `cuit_cuil`, `rol`, `fecha_nac`, `edad`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('Alumno','Tres','direccion Alumno 3','alumno@tres.com','22555444','$2a$10$sT3IZvFLmODfSX82msbHb./lE3OU0.HhiARJ.iuMFfEtKmoQigAim','20225554447','ESTUDIANTE','1990/09/01','30','ACTIVO','1',sysdate());
INSERT INTO `usuario`(`nombre`, `apellido`, `direccion`, `email`, `dni`, `contraseña`, `cuit_cuil`, `rol`, `fecha_nac`, `edad`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('Alumno','Cuatro','direccion Alumno 4','alumno@cuatro.com','33111222','$2a$10$sT3IZvFLmODfSX82msbHb./lE3OU0.HhiARJ.iuMFfEtKmoQigAim','20331112227','ESTUDIANTE','1999/08/21','21','ACTIVO','1',sysdate());

INSERT INTO `usuario`(`nombre`, `apellido`, `direccion`, `email`, `dni`, `contraseña`, `cuit_cuil`, `rol`, `fecha_nac`, `edad`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('Docente','Uno','direccion Docente 1','docente@uno.com','44555666','$2a$10$sT3IZvFLmODfSX82msbHb./lE3OU0.HhiARJ.iuMFfEtKmoQigAim','20445556667','DOCENTE','1959/10/01','61','ACTIVO','1',sysdate());
INSERT INTO `usuario`(`nombre`, `apellido`, `direccion`, `email`, `dni`, `contraseña`, `cuit_cuil`, `rol`, `fecha_nac`, `edad`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('Docente','Dos','direccion Docente 2','docente@dos.com','55444666','$2a$10$sT3IZvFLmODfSX82msbHb./lE3OU0.HhiARJ.iuMFfEtKmoQigAim','20554446667','DOCENTE','1965/08/03','55','ACTIVO','1',sysdate());
INSERT INTO `usuario`(`nombre`, `apellido`, `direccion`, `email`, `dni`, `contraseña`, `cuit_cuil`, `rol`, `fecha_nac`, `edad`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('Docente','Tres','direccion Docente 3','docente@tres.com','66555444','$2a$10$sT3IZvFLmODfSX82msbHb./lE3OU0.HhiARJ.iuMFfEtKmoQigAim','20665554447','DOCENTE','1980/02/15','40','ACTIVO','1',sysdate());
INSERT INTO `usuario`(`nombre`, `apellido`, `direccion`, `email`, `dni`, `contraseña`, `cuit_cuil`, `rol`, `fecha_nac`, `edad`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('Docente','Cuatro','direccion Docente 4','docente@cuatro.com','77444111','$2a$10$sT3IZvFLmODfSX82msbHb./lE3OU0.HhiARJ.iuMFfEtKmoQigAim','20774441117','DOCENTE','1979/10/25','41','ACTIVO','1',sysdate());
INSERT INTO `usuario`(`nombre`, `apellido`, `direccion`, `email`, `dni`, `contraseña`, `cuit_cuil`, `rol`, `fecha_nac`, `edad`, `estado`, `id_secuser`, `dt_last_update`) VALUES ('Docente','Cinco','direccion Docente 5','docente@cinco.com','11555999','$2a$10$sT3IZvFLmODfSX82msbHb./lE3OU0.HhiARJ.iuMFfEtKmoQigAim','20115559997','DOCENTE','1982/11/05','38','ACTIVO','1',sysdate());

 Commit;
